name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: '8.3'
          extensions: xml, mbstring, json

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Validate PHP files (lint)
        run: |
          find . -name '*.php' -not -path './vendor/*' -print0 | xargs -0 -n1 php -l

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPUnit (strict mode)
        env:
          TEST_STRICT_ERRORS: '1'
        run: vendor/bin/phpunit --colors=always
